[book]
authors = ["Mark Veltzer <mark.veltzer@gmail.com>"]
language = "en"
src = "src"
title = "rspandoc - Rust version of pandoc"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/veltzer/rspandoc"
edit-url-template = "https://github.com/veltzer/rspandoc/edit/master/docs/{path}"
